server:
  port: 3002
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka  ## 注册到 eureka 
spring:
  application:
    name: single-coustomer  